config/routes.rb
Blog::Application.routes.draw do

  get '/auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout' 

  root to: 'pages#index'

  resources :folders, id: /.*/i

end

app/models/user.rb
class User < ActiveRecord::Base

  def self.find_or_create_from_auth_hash(auth_hash)
    user = find_or_create_by(uid: auth_hash[:uid])
    user.update nickname: auth_hash[:info][:nickname], name: auth_hash[:info][:name], email: auth_hash[:info][:email],
                token: auth_hash[:credentials][:token], token_expires_at: Time.at(auth_hash[:credentials][:expires_at]),
                refresh_token: auth_hash[:credentials][:refresh_token]
    user
  end

end

app/models/wl_api.rb
class WlApi

  BASE_URL = 'https://apis.live.net/v5.0'

  attr_reader :token

  def initialize(token)
    @token = token
  end

  def albums
    get('/me/albums')['data']
  end

  def folder(folder_id)
    get("/#{folder_id}/files")['data']
  end

  def thumbnail_url(file_id)
    get("/#{file_id}")['images'][1]['source']
  end

  private

    def get(path)
      HTTParty.get("#{BASE_URL}#{path}?access_token=#{token}")
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @_current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  # before_filter :authenticate_twitter

  # def authenticate_twitter
  #   unless current_user
  #     redirect_to 
  #   end
  # end

end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController

  def show
    @folder = WlApi.new(current_user.token).folder(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @albums = WlApi.new(current_user.token).albums
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_or_create_from_auth_hash(auth_hash)
    session[:user_id] = user.id
    redirect_to '/'
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out!"
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/folders/show.html.erb
<ol>
  <% @folder.each do |folder| %>
    <li><%= link_to folder['name'], folder_path(folder['id']) %></li>
  <% end %>
</ol>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="brand" href="#">PicBlog</a>
        <div class="nav-collapse collapse">
          <p class="navbar-text pull-right">
            <% if current_user %>
              Signed in as <%= current_user.email %>!
              <%= link_to "Sign out", signout_path %>
            <% else %>
              <%= link_to "Sign in with Windows Live", "/auth/windowslive" %>
            <% end %>
          </p>
          <ul class="nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/pages/index.html.erb
root page!